FROM postgres:13.2
RUN apt-get update && apt-get install postgis -y
RUN apt-get update && apt-get install postgresql-13-postgis-3 -y
RUN apt-get update && apt-get install postgresql-13-postgis-3-scripts -y