services:
  postgres:
    build:
      dockerfile: ./postgres/Dockerfile
      context: .
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_pgadmin
    volumes:
      - db_data5:/var/lib/postgresql/data
    ports:
      - 5438:5432
    image: postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 5059:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: local_pgadmin
    volumes:
      - pgadmin_data5:/var/lib/pgadmin
volumes:
  db_data5:
  pgadmin_data5:
